# -*- coding: utf-8 -*-
"""notebook_geracao2_recombinacao_zhang_shasha.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eSM477PYbls6WzspzO7LRH1bEHj8W2ec

# Geração 2 — recombinação orientada por Zhang–Shasha, a partir do histórico

Este notebook não gera fragmentos do zero. Ele parte da base **já validada**
(`data/banco_smiles_aromatizados.parquet`) e usa as próprias **colunas de
histórico de recombinação** (anéis-base, fragmentos, posições, pontes) como
banco de matéria-prima para propor uma **nova fase de recombinação**.

Objetivos, em ordem:

1. Reconstruir, a partir do histórico, um catálogo de **anéis individuais**
   (cada um já com seus substituintes "assados" no SMILES).
2. Representar cada anel individual como **árvore** e usar o **Zhang–Shasha**
   (Tree Edit Distance) para medir o quão diferentes duas receitas de anel são.
3. Usar essa distância como critério de seleção: **combinar pares de anéis
   estruturalmente diferentes**, para favorecer moléculas novas em vez de
   redundantes.
4. Montar as novas moléculas (anel + ponte + anel) e **validar a cada fase**,
   exatamente como o pipeline principal faz em `src/utils/validacao.py` e
   `src/utils/aromatizacao.py`: nenhuma molécula avança para a fase seguinte
   sem passar pela validação da fase atual.
5. Visualizar os números de entrada e saída de cada etapa.

> Para uma explicação didática de como o Zhang–Shasha funciona por dentro
> (numeração pós-ordem, keyroots, complexidade) e quantas combinações ele
> resolve internamente, veja o notebook
> `notebook_inicial_recombinacao_molecular (1).ipynb`, Seções 9.1 e 11.1.
> Aqui aplicamos o mesmo algoritmo com um objetivo diferente: não só medir
> distância, mas **usar a distância para decidir o que recombinar**.

## 1. Dependências
"""

# Commented out IPython magic to ensure Python compatibility.
# Rode estas células uma vez caso as bibliotecas ainda não estejam instaladas:
# %pip install rdkit
# %pip install zss

import random
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from rdkit import Chem
from zss import Node, simple_distance

# pd.set_option("display.max_columns", 100)
# pd.set_option("display.max_colwidth", 120)

random.seed(42)
np.random.seed(42)

"""## 2. Carregar a base já validada

"""

CAMINHO_PARQUET = "/content/base_daniel - base_daniel.csv"

df_base = pd.read_csv(CAMINHO_PARQUET)

print(f"Moléculas na base de entrada: {len(df_base):,}")
print(f"Colunas disponíveis: {df_base.shape[1]:,}")

display(df_base.head(3))

# Conjuntos canônicos da base, usados mais adiante para garantir que a
# Geração 2 só aceite moléculas que ainda NÃO existem na base original.
canonicos_base_complexo = set(df_base["SMILES_Canonico_Complexo"].dropna())

canonicos_base_aromatico = set()
for smi in df_base["smiles"].dropna():
    mol = Chem.MolFromSmiles(str(smi))
    if mol is not None:
        canonicos_base_aromatico.add(Chem.MolToSmiles(mol, canonical=True))

print(f"SMILES canônicos (complexo, pré-aromatização) na base: {len(canonicos_base_complexo):,}")
print(f"SMILES canônicos (aromático, forma final) na base:     {len(canonicos_base_aromatico):,}")

"""## 3. Reconstruir o catálogo de anéis a partir do histórico

Cada linha da base guarda **dois** anéis já recombinados (`Anel1` e `Anel2`),
cada um com sua base, até 3 fragmentos e suas posições, e o SMILES já
modificado (substituintes incluídos). Em vez de regenerar fragmentos do zero,
tratamos cada um desses dois anéis como uma peça reaproveitável — o mesmo
anel que apareceu como `Anel1` numa linha pode virar `Anel2` numa
recombinação nova, e vice-versa.

"""

def extrair_catalogo_aneis(df, sufixo):
    colunas = {
        "base": f"SMILES_Base_Anel{sufixo}",
        "smiles_modificado": f"SMILES_Modificado_Anel{sufixo}",
        "frag1": f"Frag_Estrutura_1_Anel{sufixo}",
        "pos1": f"Posicao_1_Anel{sufixo}",
        "frag2": f"Frag_Estrutura_2_Anel{sufixo}",
        "pos2": f"Posicao_2_Anel{sufixo}",
        "frag3": f"Frag_Estrutura_3_Anel{sufixo}",
        "pos3": f"Posicao_3_Anel{sufixo}",
    }
    sub = df[list(colunas.values())].copy()
    sub.columns = list(colunas.keys())
    sub["origem"] = f"Anel{sufixo}"
    return sub


catalogo_bruto = pd.concat(
    [extrair_catalogo_aneis(df_base, 1), extrair_catalogo_aneis(df_base, 2)],
    ignore_index=True,
)

catalogo_aneis = (
    catalogo_bruto.drop_duplicates(subset="smiles_modificado").reset_index(drop=True)
)

print(f"Anéis extraídos do histórico (Anel1 + Anel2, com repetição): {len(catalogo_bruto):,}")
print(f"Anéis únicos no catálogo (matéria-prima para a Geração 2):  {len(catalogo_aneis):,}")

display(catalogo_aneis.head(5))

"""## 4. Catálogo de pontes

As pontes (`Ponte_Estrutura`) já registradas na base também são reaproveitadas
como estão — não criamos pontes novas, só reutilizamos o que já apareceu.

"""

catalogo_pontes = (
    df_base[["ID_Ponte", "Ponte_Estrutura"]]
    .dropna()  # Remove qualquer linha que tenha valores nulos
    .drop_duplicates()
    .reset_index(drop=True)
)

# Caso "inválido" também signifique strings vazias (""), adicione este filtro:
catalogo_pontes = catalogo_pontes[catalogo_pontes["Ponte_Estrutura"].str.strip() != "#ERROR!"]
catalogo_pontes = catalogo_pontes.reset_index(drop=True)

print(f"Pontes distintas disponíveis no histórico: {len(catalogo_pontes):,}")
display(catalogo_pontes)

"""## 5. Árvore de um anel individual

Cada anel do catálogo vira uma árvore pequena: a raiz é o anel-base, e cada
posição substituída é um filho com o fragmento correspondente pendurado
embaixo.

```text
ANEL:C1CCCCC1
├── POS:2
│   └── FRAG:N
└── POS:3
    └── FRAG:Br
```

"""

def valor_valido(v):
    return pd.notna(v) and str(v).strip() not in {"", "nan", "None"}


def anel_para_arvore(row):
    raiz = Node(f"ANEL:{row['base']}")

    itens = []
    for slot in (1, 2, 3):
        frag = row[f"frag{slot}"]
        pos = row[f"pos{slot}"]
        if valor_valido(frag):
            itens.append((str(pos), str(frag)))

    for pos, frag in sorted(itens, key=lambda x: x[0]):
        no_pos = Node(f"POS:{pos}")
        no_pos.addkid(Node(f"FRAG:{frag}"))
        raiz.addkid(no_pos)

    return raiz


def tamanho_arvore(no):
    return 1 + sum(tamanho_arvore(filho) for filho in no.children)


def ted_normalizada(a, b):
    d = simple_distance(a, b)
    denom = max(tamanho_arvore(a), tamanho_arvore(b), 1)
    return d / denom


exemplo_a = anel_para_arvore(catalogo_aneis.iloc[0])
exemplo_b = anel_para_arvore(catalogo_aneis.iloc[1])

print("Anel 0:", catalogo_aneis.iloc[0]["smiles_modificado"])
print("Anel 1:", catalogo_aneis.iloc[1]["smiles_modificado"])
print("\nDistância Zhang-Shasha (normalizada):", ted_normalizada(exemplo_a, exemplo_b))

"""## 6. Árvores de todo o catálogo

Usamos a **base de entrada completa**: a árvore é construída para todos os
anéis únicos do catálogo, sem nenhum corte de amostragem. Isso é `O(N)`,
barato.

Também sorteamos uma amostra pequena de pares só para ter uma ideia de como
as distâncias se distribuem no catálogo (usada no gráfico da Seção 12) — mas
essa amostra é apenas ilustrativa. Quem decide quem entra na próxima fase é
a Seção 7, que processa a base de entrada inteira, molécula por molécula.

"""

arvores_catalogo = [anel_para_arvore(row) for _, row in catalogo_aneis.iterrows()]

print(f"Anéis no catálogo completo (base de entrada inteira): {len(catalogo_aneis):,}")
print(f"Árvores construídas: {len(arvores_catalogo):,}")

N_TOTAL = len(catalogo_aneis)
PARES_TOTAIS_POSSIVEIS = N_TOTAL * (N_TOTAL - 1) // 2
M_PARES_AMOSTRA_ILUSTRATIVA = min(5_000, PARES_TOTAIS_POSSIVEIS)

sorteador_ilustrativo = random.Random(42)
pares_vistos_ilustrativos = set()
registros_distancia = []

while len(registros_distancia) < M_PARES_AMOSTRA_ILUSTRATIVA:
    i, j = sorteador_ilustrativo.sample(range(N_TOTAL), 2)
    if i > j:
        i, j = j, i
    if (i, j) in pares_vistos_ilustrativos:
        continue
    pares_vistos_ilustrativos.add((i, j))
    d = ted_normalizada(arvores_catalogo[i], arvores_catalogo[j])
    registros_distancia.append((i, j, d))

df_pares_amostra = pd.DataFrame(registros_distancia, columns=["i", "j", "distancia"])

print(f"Pares possíveis no catálogo completo (N x (N-1) / 2): {PARES_TOTAIS_POSSIVEIS:,}")
print(f"Pares na amostra ilustrativa (só para o gráfico):     {len(df_pares_amostra):,}")
print(f"Distância normalizada — média: {df_pares_amostra['distancia'].mean():.3f}, "
      f"mínima: {df_pares_amostra['distancia'].min():.3f}, máxima: {df_pares_amostra['distancia'].max():.3f}")

"""## 7. Funções de recombinação e validação (reutilizadas em todas as gerações)

As mesmas funções usadas para montar e validar a Geração 2 do histórico
original são reaproveitadas aqui, sem alteração: `substituir_numeracao_anel`
(troca a numeração de fechamento de anel do parceiro), `validar_e_canonizar`
e `aromatizar_aneis_6_membros` (Fases A e B de validação, iguais a
`src/utils/validacao.py` e `src/utils/aromatizacao.py`). Também preparamos o
mapa de colunas que "reencaixa" o resultado de uma geração no formato de
entrada de `df_base`, para que ele possa alimentar a formação de pares da
geração seguinte.

"""

def substituir_numeracao_anel(smiles, de="1", para="2"):
    return smiles.replace(de, para)


def validar_e_canonizar(smiles):
    mol = Chem.MolFromSmiles(str(smiles))
    if mol is None:
        return None, False
    return Chem.MolToSmiles(mol, canonical=True), True


def aromatizar_aneis_6_membros(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return None

    for anel in mol.GetRingInfo().AtomRings():
        if len(anel) != 6:
            continue

        for k in range(len(anel)):
            atomo1 = anel[k]
            atomo2 = anel[(k + 1) % len(anel)]
            ligacao = mol.GetBondBetweenAtoms(atomo1, atomo2)

            if ligacao is None:
                return None

            ligacao.SetBondType(Chem.rdchem.BondType.AROMATIC)

        for idx_atomo in anel:
            mol.GetAtomWithIdx(idx_atomo).SetIsAromatic(True)

    try:
        Chem.SanitizeMol(mol)
    except Exception:
        return None

    return Chem.MolToSmiles(mol)


MAPA_COLUNAS_GERACAO_PARA_HISTORICO = {
    "base_Anel1": "SMILES_Base_Anel1",
    "smiles_modificado_Anel1": "SMILES_Modificado_Anel1",
    "frag1_Anel1": "Frag_Estrutura_1_Anel1", "pos1_Anel1": "Posicao_1_Anel1",
    "frag2_Anel1": "Frag_Estrutura_2_Anel1", "pos2_Anel1": "Posicao_2_Anel1",
    "frag3_Anel1": "Frag_Estrutura_3_Anel1", "pos3_Anel1": "Posicao_3_Anel1",
    "base_Anel2": "SMILES_Base_Anel2",
    "smiles_modificado_Anel2": "SMILES_Modificado_Anel2",
    "frag1_Anel2": "Frag_Estrutura_1_Anel2", "pos1_Anel2": "Posicao_1_Anel2",
    "frag2_Anel2": "Frag_Estrutura_2_Anel2", "pos2_Anel2": "Posicao_2_Anel2",
    "frag3_Anel2": "Frag_Estrutura_3_Anel2", "pos3_Anel2": "Posicao_3_Anel2",
}

catalogo_pontes_lista = catalogo_pontes.to_dict("records")

"""## 8. Loop de gerações — recombinar e validar até esgotar as combinações

A função `rodar_uma_geracao` empacota o ciclo completo que as Seções 3–11
(Geração 2) e a antiga Seção 14 (Geração 3) faziam manualmente, copiando e
colando código:

1. Reconstruir o catálogo de anéis a partir de **todo** o histórico
   acumulado até aqui (Geração 1 + todas as gerações já validadas) — usado
   para procurar parceiros diversos, com o máximo de variedade disponível.
2. Formar 1 par diverso (Zhang–Shasha) para cada molécula **semente**: só as
   moléculas **novas da geração anterior** (não o histórico inteiro) entram
   como semente. Se toda molécula já existente contribuísse com um candidato
   a cada rodada — como a antiga Seção 14 fazia só para a Geração 3 —, o
   número de candidatos cresceria geometricamente (a cada geração
   multiplicando por ~1/(1 − taxa de sobrevivência)) e o loop nunca
   terminaria em tempo hábil. Usando só as moléculas novas como semente, o
   número de candidatos por geração tende a **encolher** seguindo a própria
   taxa de sobrevivência, e converge para zero.
3. Montar os candidatos (anel + ponte + anel).
4. Validar em duas fases — SMILES válido/único/novo → aromatização →
   revalidação/duplicata/novidade final —, sempre contra o histórico
   **completo** acumulado (para garantir que nada duplique nenhuma geração
   anterior), exatamente como antes.

O `while` mais abaixo chama essa função geração após geração. A parada é
automática: quando uma geração inteira não produz **nenhuma** molécula nova,
não há mais semente para recombinar, e o loop encerra — essa é a condição
"não existe mais possibilidade de geração".

Ainda existe um teto de segurança (`MAX_GERACOES_SEGURANCA`), só para o caso
de a taxa de sobrevivência oscilar sem nunca chegar exatamente a zero.

"""

def rodar_uma_geracao(df_sementes, df_historico_completo, catalogo_pontes_lista,
                       canonicos_complexo_conhecidos, canonicos_aromatico_conhecidos,
                       numero_geracao, n_sondas=10, semente=44):
    catalogo_bruto = pd.concat(
        [extrair_catalogo_aneis(df_historico_completo, 1),
         extrair_catalogo_aneis(df_historico_completo, 2)],
        ignore_index=True,
    )
    catalogo_aneis_geracao = catalogo_bruto.drop_duplicates(subset="smiles_modificado").reset_index(drop=True)
    arvores_catalogo_geracao = [anel_para_arvore(row) for _, row in catalogo_aneis_geracao.iterrows()]
    n_catalogo = len(catalogo_aneis_geracao)

    # Só as moleculas SEMENTES (novas da geracao anterior) contribuem com um
    # candidato cada -- nao o historico inteiro. Isso evita que o numero de
    # candidatos cresca geometricamente a cada rodada (ver Secao 8).
    base_anel1_geracao = extrair_catalogo_aneis(df_sementes, 1)

    sorteador_pares = random.Random(semente)
    n_sondas_efetivo = min(n_sondas, n_catalogo)
    pares_registros = []
    for pos in range(len(base_anel1_geracao)):
        row_i = base_anel1_geracao.iloc[pos]
        arvore_i = anel_para_arvore(row_i)
        indices_sondados = sorteador_pares.sample(range(n_catalogo), n_sondas_efetivo)
        distancias_sondadas = [
            (idx, ted_normalizada(arvore_i, arvores_catalogo_geracao[idx]))
            for idx in indices_sondados
        ]
        melhor_idx, melhor_distancia = max(distancias_sondadas, key=lambda par: par[1])
        pares_registros.append({"pos_base": pos, "j": melhor_idx, "distancia": melhor_distancia})
    df_pares_geracao = pd.DataFrame(pares_registros)

    sorteador_pontes = random.Random(semente * 7 + 1)
    registros_novos = []
    for _, par in df_pares_geracao.iterrows():
        row_i = base_anel1_geracao.iloc[int(par["pos_base"])]
        row_j = catalogo_aneis_geracao.iloc[int(par["j"])]
        ponte = sorteador_pontes.choice(catalogo_pontes_lista)

        smi_i = row_i["smiles_modificado"]
        smi_j = substituir_numeracao_anel(row_j["smiles_modificado"])
        smiles_complexo = f"{smi_i}{ponte['Ponte_Estrutura']}{smi_j}"

        registros_novos.append({
            "base_Anel1": row_i["base"], "smiles_modificado_Anel1": row_i["smiles_modificado"],
            "frag1_Anel1": row_i["frag1"], "pos1_Anel1": row_i["pos1"],
            "frag2_Anel1": row_i["frag2"], "pos2_Anel1": row_i["pos2"],
            "frag3_Anel1": row_i["frag3"], "pos3_Anel1": row_i["pos3"],
            "ID_Ponte": ponte["ID_Ponte"], "Ponte_Estrutura": ponte["Ponte_Estrutura"],
            "base_Anel2": row_j["base"], "smiles_modificado_Anel2": row_j["smiles_modificado"],
            "frag1_Anel2": row_j["frag1"], "pos1_Anel2": row_j["pos1"],
            "frag2_Anel2": row_j["frag2"], "pos2_Anel2": row_j["pos2"],
            "frag3_Anel2": row_j["frag3"], "pos3_Anel2": row_j["pos3"],
            "distancia_ted_normalizada": par["distancia"],
            "SMILES_Complexo": smiles_complexo,
        })
    df_candidatos_geracao = pd.DataFrame(registros_novos)

    # Fase A -- SMILES valido / unico na leva / realmente novo
    tentativas = len(df_candidatos_geracao)
    removidos_invalidos = 0
    removidos_duplicata_interna = 0
    removidos_ja_existentes = 0
    vistos_internos = set()
    linhas_validas = []
    canonicos_validos = []

    for _, row in df_candidatos_geracao.iterrows():
        canonico, valido = validar_e_canonizar(row["SMILES_Complexo"])
        if not valido:
            removidos_invalidos += 1
            continue
        if canonico in vistos_internos:
            removidos_duplicata_interna += 1
            continue
        if canonico in canonicos_complexo_conhecidos:
            removidos_ja_existentes += 1
            continue
        vistos_internos.add(canonico)
        linhas_validas.append(row)
        canonicos_validos.append(canonico)

    df_fase_a = pd.DataFrame(linhas_validas).reset_index(drop=True)
    df_fase_a["SMILES_Canonico_Complexo_Candidato"] = canonicos_validos

    # Fase B -- aromatizacao + revalidacao + duplicata/novidade final
    if len(df_fase_a) > 0:
        df_fase_a["SMILES_Aromatico_Candidato"] = df_fase_a["SMILES_Complexo"].apply(aromatizar_aneis_6_membros)
    else:
        df_fase_a["SMILES_Aromatico_Candidato"] = pd.Series(dtype=object)

    antes_aromatizacao = len(df_fase_a)
    df_fase_b = df_fase_a.dropna(subset=["SMILES_Aromatico_Candidato"]).reset_index(drop=True)
    removidos_aromatizacao = antes_aromatizacao - len(df_fase_b)

    vistos_finais = set()
    removidos_nao_revalidados = 0
    removidos_duplicata_pos_aromatizacao = 0
    removidos_ja_existentes_pos_aromatizacao = 0
    linhas_finais = []

    for _, row in df_fase_b.iterrows():
        mol = Chem.MolFromSmiles(row["SMILES_Aromatico_Candidato"])
        if mol is None:
            removidos_nao_revalidados += 1
            continue
        canonico_final = Chem.MolToSmiles(mol, canonical=True)
        if canonico_final in vistos_finais:
            removidos_duplicata_pos_aromatizacao += 1
            continue
        if canonico_final in canonicos_aromatico_conhecidos:
            removidos_ja_existentes_pos_aromatizacao += 1
            continue
        vistos_finais.add(canonico_final)
        linhas_finais.append(row)

    df_geracao = pd.DataFrame(linhas_finais).reset_index(drop=True)
    if len(df_geracao) > 0:
        df_geracao["smiles"] = df_geracao["SMILES_Aromatico_Candidato"]
    df_geracao["Geracao"] = numero_geracao

    estatisticas = {
        "geracao": numero_geracao,
        "sementes_entrada": len(df_sementes),
        "historico_completo_no_momento": len(df_historico_completo),
        "catalogo_aneis_disponivel": n_catalogo,
        "candidatos_gerados": tentativas,
        "distancia_media_pares": df_pares_geracao["distancia"].mean() if tentativas else float("nan"),
        "removidos_invalidos": removidos_invalidos,
        "removidos_duplicata_interna": removidos_duplicata_interna,
        "removidos_ja_existentes": removidos_ja_existentes,
        "validos_apos_fase_a": len(df_fase_a),
        "removidos_falha_aromatizacao": removidos_aromatizacao,
        "validos_apos_aromatizacao": len(df_fase_b),
        "removidos_nao_revalidados": removidos_nao_revalidados,
        "removidos_duplicata_pos_aromatizacao": removidos_duplicata_pos_aromatizacao,
        "removidos_ja_existentes_pos_aromatizacao": removidos_ja_existentes_pos_aromatizacao,
        "moleculas_novas": len(df_geracao),
        "taxa_sobrevivencia": (len(df_geracao) / tentativas) if tentativas else 0.0,
    }

    return df_geracao, estatisticas

def rodar_uma_geracao(df_sementes, df_historico_completo, catalogo_pontes_lista,
                       canonicos_complexo_conhecidos, canonicos_aromatico_conhecidos,
                       numero_geracao, n_sondas=10, semente=44):

    catalogo_bruto = pd.concat(
        [extrair_catalogo_aneis(df_historico_completo, 1),
         extrair_catalogo_aneis(df_historico_completo, 2)],
        ignore_index=True,
    )
    catalogo_aneis_geracao = catalogo_bruto.drop_duplicates(subset="smiles_modificado").reset_index(drop=True)
    arvores_catalogo_geracao = [anel_para_arvore(row) for _, row in catalogo_aneis_geracao.iterrows()]
    n_catalogo = len(catalogo_aneis_geracao)

    # Só as moleculas SEMENTES da geração anterior contribuem com um candidato base
    base_anel1_geracao = extrair_catalogo_aneis(df_sementes, 1)

    sorteador_pares = random.Random(semente)
    sorteador_pontes = random.Random(semente * 7 + 1)

    n_sondas_efetivo = min(n_sondas, n_catalogo)

    # Variáveis para a validação imediata (Fase A integrada com o "Rebote")
    vistos_internos = set()
    linhas_validas = []
    canonicos_validos = []

    # Contadores de estatísticas atualizados
    removidos_invalidos = 0
    removidos_duplicata_interna = 0
    removidos_ja_existentes = 0
    tentativas_totais = 0

    for pos in range(len(base_anel1_geracao)):
        row_i = base_anel1_geracao.iloc[pos]
        arvore_i = anel_para_arvore(row_i)

        indices_sondados = sorteador_pares.sample(range(n_catalogo), n_sondas_efetivo)

        distancias_sondadas = [
            (idx, ted_normalizada(arvore_i, arvores_catalogo_geracao[idx]))
            for idx in indices_sondados
        ]

        # Ordena decrescente pela distância de edição (maior diversidade primeiro)
        distancias_sondadas.sort(key=lambda par: par[1], reverse=True)

        # O "Rebote": Tenta formar a molécula descendo a lista até achar uma válida
        for melhor_idx, melhor_distancia in distancias_sondadas:
            tentativas_totais += 1

            row_j = catalogo_aneis_geracao.iloc[melhor_idx]
            ponte = sorteador_pontes.choice(catalogo_pontes_lista)

            smi_i = row_i["smiles_modificado"]
            smi_j = substituir_numeracao_anel(row_j["smiles_modificado"])
            smiles_complexo = f"{smi_i}{ponte['Ponte_Estrutura']}{smi_j}"

            canonico, valido = validar_e_canonizar(smiles_complexo)

            if not valido:
                removidos_invalidos += 1
                continue # Falhou sintaticamente, tenta o próximo anel da lista

            if canonico in vistos_internos:
                removidos_duplicata_interna += 1
                continue # Repetido na mesma rodada, tenta o próximo

            if canonico in canonicos_complexo_conhecidos:
                removidos_ja_existentes += 1
                continue # Já gerado em gerações passadas, tenta o próximo

            # Se chegou aqui, a molécula é VÁLIDA e INÉDITA!
            vistos_internos.add(canonico)
            canonicos_validos.append(canonico)

            linhas_validas.append({
                "base_Anel1": row_i["base"], "smiles_modificado_Anel1": row_i["smiles_modificado"],
                "frag1_Anel1": row_i["frag1"], "pos1_Anel1": row_i["pos1"],
                "frag2_Anel1": row_i["frag2"], "pos2_Anel1": row_i["pos2"],
                "frag3_Anel1": row_i["frag3"], "pos3_Anel1": row_i["pos3"],
                "ID_Ponte": ponte["ID_Ponte"], "Ponte_Estrutura": ponte["Ponte_Estrutura"],
                "base_Anel2": row_j["base"], "smiles_modificado_Anel2": row_j["smiles_modificado"],
                "frag1_Anel2": row_j["frag1"], "pos1_Anel2": row_j["pos1"],
                "frag2_Anel2": row_j["frag2"], "pos2_Anel2": row_j["pos2"],
                "frag3_Anel2": row_j["frag3"], "pos3_Anel2": row_j["pos3"],
                "distancia_ted_normalizada": melhor_distancia,
                "SMILES_Complexo": smiles_complexo,
            })

            # Achou um par válido para esta semente, quebra o loop interno e vai pra próxima semente
            break

    df_fase_a = pd.DataFrame(linhas_validas)

    # Prevenção de erro caso NENHUMA molécula passe (df_fase_a vazio)
    if not df_fase_a.empty:
        df_fase_a["SMILES_Canonico_Complexo_Candidato"] = canonicos_validos
    else:
        df_fase_a = pd.DataFrame(columns=["SMILES_Complexo", "distancia_ted_normalizada", "SMILES_Canonico_Complexo_Candidato"])

    # Fase B -- aromatizacao + revalidacao + duplicata/novidade final
    if len(df_fase_a) > 0:
        df_fase_a["SMILES_Aromatico_Candidato"] = df_fase_a["SMILES_Complexo"].apply(aromatizar_aneis_6_membros)
    else:
        df_fase_a["SMILES_Aromatico_Candidato"] = pd.Series(dtype=object)

    antes_aromatizacao = len(df_fase_a)
    df_fase_b = df_fase_a.dropna(subset=["SMILES_Aromatico_Candidato"]).reset_index(drop=True)
    removidos_aromatizacao = antes_aromatizacao - len(df_fase_b)

    vistos_finais = set()
    removidos_nao_revalidados = 0
    removidos_duplicata_pos_aromatizacao = 0
    removidos_ja_existentes_pos_aromatizacao = 0
    linhas_finais = []

    for _, row in df_fase_b.iterrows():
        mol = Chem.MolFromSmiles(row["SMILES_Aromatico_Candidato"])
        if mol is None:
            removidos_nao_revalidados += 1
            continue
        canonico_final = Chem.MolToSmiles(mol, canonical=True)
        if canonico_final in vistos_finais:
            removidos_duplicata_pos_aromatizacao += 1
            continue
        if canonico_final in canonicos_aromatico_conhecidos:
            removidos_ja_existentes_pos_aromatizacao += 1
            continue
        vistos_finais.add(canonico_final)
        linhas_finais.append(row)

    df_geracao = pd.DataFrame(linhas_finais).reset_index(drop=True)

    if len(df_geracao) > 0:
        df_geracao["smiles"] = df_geracao["SMILES_Aromatico_Candidato"]
    else:
        df_geracao = pd.DataFrame(columns=["smiles"])

    df_geracao["Geracao"] = numero_geracao

    # Consolidação das Estatísticas com os novos contadores
    tentativas = tentativas_totais
    distancia_media = df_fase_a["distancia_ted_normalizada"].mean() if not df_fase_a.empty else float("nan")

    estatisticas = {
        "geracao": numero_geracao,
        "sementes_entrada": len(df_sementes),
        "historico_completo_no_momento": len(df_historico_completo),
        "catalogo_aneis_disponivel": n_catalogo,
        "candidatos_gerados": tentativas, # Chave corrigida
        "distancia_media_pares": distancia_media,
        "removidos_invalidos": removidos_invalidos,
        "removidos_duplicata_interna": removidos_duplicata_interna,
        "removidos_ja_existentes": removidos_ja_existentes,
        "validos_apos_fase_a": len(df_fase_a),
        "removidos_falha_aromatizacao": removidos_aromatizacao,
        "validos_apos_aromatizacao": len(df_fase_b),
        "removidos_nao_revalidados": removidos_nao_revalidados,
        "removidos_duplicata_pos_aromatizacao": removidos_duplicata_pos_aromatizacao,
        "removidos_ja_existentes_pos_aromatizacao": removidos_ja_existentes_pos_aromatizacao,
        "moleculas_novas": len(df_geracao),
        "taxa_sobrevivencia": (len(df_geracao) / tentativas) if tentativas > 0 else 0.0,
    }

    return df_geracao, estatisticas

def rodar_uma_geracao(df_sementes, df_historico_completo, catalogo_pontes_lista,
                       canonicos_complexo_conhecidos, canonicos_aromatico_conhecidos,
                       numero_geracao, n_sondas=10, semente=44,
                       combinacoes_invalidas_conhecidas=None): # NOVO PARAMETRO

    # Inicializa a memória de falhas caso não seja passada
    if combinacoes_invalidas_conhecidas is None:
        combinacoes_invalidas_conhecidas = set()

    catalogo_bruto = pd.concat(
        [extrair_catalogo_aneis(df_historico_completo, 1),
         extrair_catalogo_aneis(df_historico_completo, 2)],
        ignore_index=True,
    )
    catalogo_aneis_geracao = catalogo_bruto.drop_duplicates(subset="smiles_modificado").reset_index(drop=True)
    arvores_catalogo_geracao = [anel_para_arvore(row) for _, row in catalogo_aneis_geracao.iterrows()]
    n_catalogo = len(catalogo_aneis_geracao)

    base_anel1_geracao = extrair_catalogo_aneis(df_sementes, 1)

    sorteador_pares = random.Random(semente)
    sorteador_pontes = random.Random(semente * 7 + 1)

    n_sondas_efetivo = min(n_sondas, n_catalogo)

    vistos_internos = set()
    linhas_validas = []
    canonicos_validos = []

    removidos_invalidos = 0
    removidos_duplicata_interna = 0
    removidos_ja_existentes = 0
    tentativas_totais = 0

    for pos in range(len(base_anel1_geracao)):
        row_i = base_anel1_geracao.iloc[pos]
        arvore_i = anel_para_arvore(row_i)

        indices_sondados = sorteador_pares.sample(range(n_catalogo), n_sondas_efetivo)

        distancias_sondadas = [
            (idx, ted_normalizada(arvore_i, arvores_catalogo_geracao[idx]))
            for idx in indices_sondados
        ]

        distancias_sondadas.sort(key=lambda par: par[1], reverse=True)

        for melhor_idx, melhor_distancia in distancias_sondadas:
            tentativas_totais += 1

            row_j = catalogo_aneis_geracao.iloc[melhor_idx]
            ponte = sorteador_pontes.choice(catalogo_pontes_lista)

            smi_i = row_i["smiles_modificado"]
            smi_j = substituir_numeracao_anel(row_j["smiles_modificado"])

            # CRIA UMA ASSINATURA DA COMBINAÇÃO ATUAL
            assinatura_comb = (smi_i, ponte['Ponte_Estrutura'], smi_j)

            # MEMÓRIA: Verifica se essa combinação já quebrou antes
            if assinatura_comb in combinacoes_invalidas_conhecidas:
                removidos_invalidos += 1
                continue # Pula o RDKit e vai direto para a próxima sonda

            smiles_complexo = f"{smi_i}{ponte['Ponte_Estrutura']}{smi_j}"
            canonico, valido = validar_e_canonizar(smiles_complexo)

            if not valido:
                # APRENDIZADO: Registra a falha para nunca mais tentar essa exata junção
                combinacoes_invalidas_conhecidas.add(assinatura_comb)
                removidos_invalidos += 1
                continue

            if canonico in vistos_internos:
                removidos_duplicata_interna += 1
                continue

            if canonico in canonicos_complexo_conhecidos:
                removidos_ja_existentes += 1
                continue

            vistos_internos.add(canonico)
            canonicos_validos.append(canonico)

            linhas_validas.append({
                "base_Anel1": row_i["base"], "smiles_modificado_Anel1": row_i["smiles_modificado"],
                "frag1_Anel1": row_i["frag1"], "pos1_Anel1": row_i["pos1"],
                "frag2_Anel1": row_i["frag2"], "pos2_Anel1": row_i["pos2"],
                "frag3_Anel1": row_i["frag3"], "pos3_Anel1": row_i["pos3"],
                "ID_Ponte": ponte["ID_Ponte"], "Ponte_Estrutura": ponte["Ponte_Estrutura"],
                "base_Anel2": row_j["base"], "smiles_modificado_Anel2": row_j["smiles_modificado"],
                "frag1_Anel2": row_j["frag1"], "pos1_Anel2": row_j["pos1"],
                "frag2_Anel2": row_j["frag2"], "pos2_Anel2": row_j["pos2"],
                "frag3_Anel2": row_j["frag3"], "pos3_Anel2": row_j["pos3"],
                "distancia_ted_normalizada": melhor_distancia,
                "SMILES_Complexo": smiles_complexo,
            })

            break

    df_fase_a = pd.DataFrame(linhas_validas)

    if not df_fase_a.empty:
        df_fase_a["SMILES_Canonico_Complexo_Candidato"] = canonicos_validos
    else:
        df_fase_a = pd.DataFrame(columns=["SMILES_Complexo", "distancia_ted_normalizada", "SMILES_Canonico_Complexo_Candidato"])

    if len(df_fase_a) > 0:
        df_fase_a["SMILES_Aromatico_Candidato"] = df_fase_a["SMILES_Complexo"].apply(aromatizar_aneis_6_membros)
    else:
        df_fase_a["SMILES_Aromatico_Candidato"] = pd.Series(dtype=object)

    antes_aromatizacao = len(df_fase_a)
    df_fase_b = df_fase_a.dropna(subset=["SMILES_Aromatico_Candidato"]).reset_index(drop=True)
    removidos_aromatizacao = antes_aromatizacao - len(df_fase_b)

    vistos_finais = set()
    removidos_nao_revalidados = 0
    removidos_duplicata_pos_aromatizacao = 0
    removidos_ja_existentes_pos_aromatizacao = 0
    linhas_finais = []

    for _, row in df_fase_b.iterrows():
        mol = Chem.MolFromSmiles(row["SMILES_Aromatico_Candidato"])
        if mol is None:
            removidos_nao_revalidados += 1
            continue
        canonico_final = Chem.MolToSmiles(mol, canonical=True)
        if canonico_final in vistos_finais:
            removidos_duplicata_pos_aromatizacao += 1
            continue
        if canonico_final in canonicos_aromatico_conhecidos:
            removidos_ja_existentes_pos_aromatizacao += 1
            continue
        vistos_finais.add(canonico_final)
        linhas_finais.append(row)

    df_geracao = pd.DataFrame(linhas_finais).reset_index(drop=True)

    if len(df_geracao) > 0:
        df_geracao["smiles"] = df_geracao["SMILES_Aromatico_Candidato"]
    else:
        df_geracao = pd.DataFrame(columns=["smiles"])

    df_geracao["Geracao"] = numero_geracao

    tentativas = tentativas_totais
    distancia_media = df_fase_a["distancia_ted_normalizada"].mean() if not df_fase_a.empty else float("nan")

    estatisticas = {
        "geracao": numero_geracao,
        "sementes_entrada": len(df_sementes),
        "historico_completo_no_momento": len(df_historico_completo),
        "catalogo_aneis_disponivel": n_catalogo,
        "candidatos_gerados": tentativas,
        "distancia_media_pares": distancia_media,
        "removidos_invalidos": removidos_invalidos,
        "removidos_duplicata_interna": removidos_duplicata_interna,
        "removidos_ja_existentes": removidos_ja_existentes,
        "validos_apos_fase_a": len(df_fase_a),
        "removidos_falha_aromatizacao": removidos_aromatizacao,
        "validos_apos_aromatizacao": len(df_fase_b),
        "removidos_nao_revalidados": removidos_nao_revalidados,
        "removidos_duplicata_pos_aromatizacao": removidos_duplicata_pos_aromatizacao,
        "removidos_ja_existentes_pos_aromatizacao": removidos_ja_existentes_pos_aromatizacao,
        "moleculas_novas": len(df_geracao),
        "taxa_sobrevivencia": (len(df_geracao) / tentativas) if tentativas > 0 else 0.0,
    }

    return df_geracao, estatisticas

MAX_GERACOES_SEGURANCA = 40  # teto de seguranca -- caso a sobrevivencia oscile
                              # sem nunca chegar a exatamente zero.
N_SONDAS_LOOP = 10
SEMENTE_BASE = 44

historico_por_geracao = {1: df_base}
df_historico_acumulado = df_base.copy()
df_sementes_atual = df_base  # Geracao 1 inteira e a semente da Geracao 2
canonicos_complexo_acumulado = set(canonicos_base_complexo)
canonicos_aromatico_acumulado = set(canonicos_base_aromatico)

metricas_geracoes = []
geracao_atual = 1
motivo_parada = None

while geracao_atual < 1 + MAX_GERACOES_SEGURANCA:
    proxima_geracao = geracao_atual + 1

    df_geracao_nova, estatisticas = rodar_uma_geracao(
        df_sementes_atual,
        df_historico_acumulado,
        catalogo_pontes_lista,
        canonicos_complexo_acumulado,
        canonicos_aromatico_acumulado,
        numero_geracao=proxima_geracao,
        n_sondas=N_SONDAS_LOOP,
        semente=SEMENTE_BASE + proxima_geracao,
    )
    metricas_geracoes.append(estatisticas)

    n_nova = estatisticas["moleculas_novas"]
    tentativas = estatisticas["candidatos_gerados"]
    taxa = estatisticas["taxa_sobrevivencia"]
    print(f"Geracao {proxima_geracao}: {tentativas:,} candidatos (sementes: {estatisticas['sementes_entrada']:,}) "
          f"-> {n_nova:,} moleculas novas (sobrevivencia {taxa:.1%})")

    if n_nova == 0:
        motivo_parada = "sem_moleculas_novas"
        print(f"\nGeracao {proxima_geracao} nao produziu nenhuma molecula nova -- "
              f"nao ha mais possibilidade de geracao. Loop encerrado.")
        break

    historico_por_geracao[proxima_geracao] = df_geracao_nova
    canonicos_complexo_acumulado |= set(df_geracao_nova["SMILES_Canonico_Complexo_Candidato"])
    canonicos_aromatico_acumulado |= set(df_geracao_nova["smiles"])

    df_geracao_renomeada = df_geracao_nova.rename(columns=MAPA_COLUNAS_GERACAO_PARA_HISTORICO)
    df_historico_acumulado = pd.concat([df_historico_acumulado, df_geracao_renomeada], ignore_index=True)
    df_sementes_atual = df_geracao_renomeada  # so as moleculas novas desta rodada viram semente da proxima

    geracao_atual = proxima_geracao
else:
    motivo_parada = "teto_de_seguranca"
    print(f"\nAtingido o teto de seguranca de {MAX_GERACOES_SEGURANCA} geracoes novas "
          f"sem a sobrevivencia chegar a zero. Loop encerrado por seguranca.")

ultima_geracao = geracao_atual
print(f"\nTotal de geracoes novas geradas com sucesso: {ultima_geracao - 1}")
print(f"Motivo da parada: {motivo_parada}")

"""## 9. Métricas finais — todas as gerações

Números consolidados do loop inteiro: quantas árvores (candidatos anel +
ponte + anel) foram montadas e validadas no total, quantas sobreviveram,
qual a porcentagem de sobrevivência (por geração e global) e qual o valor
final da base depois de rodar até não haver mais possibilidade de geração.

"""

df_metricas_geracoes = pd.DataFrame(metricas_geracoes)

total_candidatos_tentados = int(df_metricas_geracoes["candidatos_gerados"].sum())
total_moleculas_novas = int(df_metricas_geracoes["moleculas_novas"].sum())
taxa_sobrevivencia_global = (total_moleculas_novas / total_candidatos_tentados
                              if total_candidatos_tentados else 0.0)

n_geracoes_novas = len(df_metricas_geracoes)
n_geracoes_com_sucesso = int((df_metricas_geracoes["moleculas_novas"] > 0).sum())

tamanho_base_original = len(df_base)
tamanho_final_total = tamanho_base_original + total_moleculas_novas
crescimento_total = total_moleculas_novas / tamanho_base_original

print("=" * 70)
print("RESUMO FINAL -- LOOP DE GERACOES")
print("=" * 70)
print(f"Base original (Geracao 1):                        {tamanho_base_original:,} moleculas")
print(f"Geracoes novas tentadas (ate a parada):            {n_geracoes_novas}")
print(f"Geracoes que produziram ao menos 1 molecula nova:  {n_geracoes_com_sucesso}")
print(f"Motivo da parada:                                  {motivo_parada}")
print("-" * 70)
print(f"Total de arvores/candidatos gerados (todas as geracoes): {total_candidatos_tentados:,}")
print(f"Total de moleculas novas validadas (todas as geracoes):  {total_moleculas_novas:,}")
print(f"Porcentagem de sobrevivencia global:                      {taxa_sobrevivencia_global:.2%}")
print("-" * 70)
print(f"Valor final (base + todas as geracoes novas):      {tamanho_final_total:,} moleculas")
print(f"Crescimento em relacao a base original:            {crescimento_total:.2%}")
print("=" * 70)

display(df_metricas_geracoes)

df_metricas_geracoes["moleculas_acumuladas"] = (
    tamanho_base_original + df_metricas_geracoes["moleculas_novas"].cumsum()
)
df_metricas_geracoes["candidatos_acumulados"] = df_metricas_geracoes["candidatos_gerados"].cumsum()
df_metricas_geracoes["moleculas_novas_acumuladas"] = df_metricas_geracoes["moleculas_novas"].cumsum()
df_metricas_geracoes["taxa_sobrevivencia_acumulada"] = (
    df_metricas_geracoes["moleculas_novas_acumuladas"] / df_metricas_geracoes["candidatos_acumulados"]
)

display(df_metricas_geracoes[[
    "geracao", "sementes_entrada", "catalogo_aneis_disponivel",
    "candidatos_gerados", "moleculas_novas", "taxa_sobrevivencia",
    "moleculas_acumuladas", "taxa_sobrevivencia_acumulada",
]])

"""## 10. Exportar todas as gerações

"""

CAMINHO_SAIDA_METRICAS = Path("data/metricas_geracoes_loop.parquet")
CAMINHO_SAIDA_METRICAS.parent.mkdir(parents=True, exist_ok=True)
df_metricas_geracoes.to_parquet(CAMINHO_SAIDA_METRICAS, index=False)
print(f"Metricas por geracao exportadas para: {CAMINHO_SAIDA_METRICAS.resolve()}")

for numero, df_ger in historico_por_geracao.items():
    if numero == 1:
        continue  # Geracao 1 e a base original, ja existe em disco
    caminho = Path(f"data/banco_smiles_geracao{numero}.parquet")
    df_ger.to_parquet(caminho, index=False)
    print(f"Geracao {numero} exportada para: {caminho.resolve()} ({len(df_ger):,} moleculas)")

"""## 11. Visualizações

Mesma paleta usada no restante do notebook (azul e laranja para identidade,
rampa ordinal de azul para os estágios), agora aplicada a todas as gerações
do loop, não só a duas.

"""

PALETA = {
    "azul": "#2a78d6",
    "laranja": "#eb6834",
    "sequencial": "#3987e5",
    "ordinal_funil": ["#86b6ef", "#6da7ec", "#5598e7", "#3987e5", "#2a78d6", "#256abf"],
    "grade": "#e1e0d9",
    "eixo": "#c3c2b7",
    "texto_primario": "#0b0b0b",
    "texto_secundario": "#52514e",
}


def estilizar_eixos(ax):
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.spines["left"].set_color(PALETA["eixo"])
    ax.spines["bottom"].set_color(PALETA["eixo"])
    ax.tick_params(colors=PALETA["texto_secundario"])
    ax.xaxis.label.set_color(PALETA["texto_secundario"])
    ax.yaxis.label.set_color(PALETA["texto_secundario"])
    ax.title.set_color(PALETA["texto_primario"])

categorias_geracoes = ["Geracao 1\n(base)"] + [f"Geracao {g}" for g in df_metricas_geracoes["geracao"]]
valores_geracoes = [tamanho_base_original] + list(df_metricas_geracoes["moleculas_novas"])
cores_geracoes = [PALETA["azul"]] + [
    PALETA["ordinal_funil"][i % len(PALETA["ordinal_funil"])] for i in range(len(df_metricas_geracoes))
]

fig, ax = plt.subplots(figsize=(max(6, 1.1 * len(categorias_geracoes)), 5))
barras = ax.bar(categorias_geracoes, valores_geracoes, color=cores_geracoes, width=0.6)

for barra, valor in zip(barras, valores_geracoes):
    altura = barra.get_height()
    ax.text(
        barra.get_x() + barra.get_width() / 2,
        altura * 1.05 if altura > 0 else 0.5,
        f"{valor:,}",
        ha="center",
        color=PALETA["texto_primario"],
        fontsize=9,
    )

ax.set_ylabel("Moleculas (escala log)")
ax.set_yscale("log")
ax.set_title("Moleculas novas por geracao -- ate esgotar as combinacoes")
ax.grid(axis="y", color=PALETA["grade"], linewidth=0.8, which="both")
ax.set_axisbelow(True)
estilizar_eixos(ax)
plt.xticks(rotation=45, ha="right")
plt.tight_layout()
plt.show()

fig, ax = plt.subplots(figsize=(9, 4.5))
ax.plot(df_metricas_geracoes["geracao"], df_metricas_geracoes["taxa_sobrevivencia"] * 100,
        marker="o", color=PALETA["azul"], label="Sobrevivencia por geracao")
ax.plot(df_metricas_geracoes["geracao"], df_metricas_geracoes["taxa_sobrevivencia_acumulada"] * 100,
        marker="o", color=PALETA["laranja"], linestyle="--", label="Sobrevivencia acumulada")

ax.set_xlabel("Geracao")
ax.set_ylabel("Taxa de sobrevivencia (%)")
ax.set_title("Taxa de sobrevivencia ao longo das geracoes")
ax.legend(frameon=False, labelcolor=PALETA["texto_secundario"])
ax.grid(axis="y", color=PALETA["grade"], linewidth=0.8)
ax.set_axisbelow(True)
estilizar_eixos(ax)
plt.tight_layout()
plt.show()

largura = 0.35
posicoes = range(len(df_metricas_geracoes))

fig, ax = plt.subplots(figsize=(max(6, 1.1 * len(df_metricas_geracoes)), 5))
ax.bar([p - largura / 2 for p in posicoes], df_metricas_geracoes["candidatos_gerados"],
       width=largura, color=PALETA["ordinal_funil"][0], label="Candidatos gerados")
ax.bar([p + largura / 2 for p in posicoes], df_metricas_geracoes["moleculas_novas"],
       width=largura, color=PALETA["laranja"], label="Moleculas novas validadas")

ax.set_xticks(list(posicoes))
ax.set_xticklabels([f"Ger. {g}" for g in df_metricas_geracoes["geracao"]], rotation=45, ha="right")
ax.set_ylabel("Quantidade")
ax.set_title("Candidatos tentados vs. moleculas novas validadas, por geracao")
ax.legend(frameon=False, labelcolor=PALETA["texto_secundario"])
ax.grid(axis="y", color=PALETA["grade"], linewidth=0.8)
ax.set_axisbelow(True)
estilizar_eixos(ax)
plt.tight_layout()
plt.show()

fig, ax = plt.subplots(figsize=(9, 4.5))
eixo_x = [1] + list(df_metricas_geracoes["geracao"])
eixo_y = [tamanho_base_original] + list(df_metricas_geracoes["moleculas_acumuladas"])

ax.plot(eixo_x, eixo_y, marker="o", color=PALETA["azul"])
ax.set_xlabel("Geracao")
ax.set_ylabel("Total de moleculas acumuladas")
ax.set_title("Crescimento acumulado da base ao longo das geracoes")
ax.grid(axis="y", color=PALETA["grade"], linewidth=0.8)
ax.set_axisbelow(True)
estilizar_eixos(ax)
plt.tight_layout()
plt.show()

"""## 12. Conclusão

O loop refaz, geração após geração, o mesmo ciclo que a versão anterior
deste notebook fazia manualmente para a Geração 3: reconstruir o catálogo a
partir do histórico acumulado, formar pares diversos por Zhang–Shasha,
montar candidatos e validar em duas fases contra tudo que já existe. A
diferença é que, a cada rodada, só as moléculas **novas** da geração
anterior viram semente para os próximos candidatos (não o histórico
inteiro) — isso evita que o número de candidatos exploda geometricamente, e
faz o loop convergir sozinho até a condição de parada: uma geração inteira
sem nenhuma molécula nova, ou o teto de segurança, o que vier primeiro.

"""

print("CONCLUSAO")
print("-" * 70)
print(f"O loop rodou {n_geracoes_novas} geracao(oes) nova(s) a partir da base "
      f"original de {tamanho_base_original:,} moleculas. A cada rodada, so as "
      f"moleculas novas da geracao anterior viraram semente para novos "
      f"candidatos (buscando parceiros em todo o catalogo historico), o que "
      f"faz o numero de candidatos encolher a cada geracao ate convergir.")
print()
if motivo_parada == "sem_moleculas_novas":
    detalhe_parada = "nenhuma molecula nova sobreviveu na ultima geracao testada"
else:
    detalhe_parada = f"teto de seguranca de {MAX_GERACOES_SEGURANCA} geracoes novas atingido"
print(f"Parada: {motivo_parada} ({detalhe_parada}).")
print()
print(f"No total, {total_candidatos_tentados:,} arvores (anel + ponte + anel) foram "
      f"montadas e validadas ao longo de todas as geracoes; {total_moleculas_novas:,} "
      f"sobreviveram as duas fases de validacao -- uma sobrevivencia global de "
      f"{taxa_sobrevivencia_global:.2%}.")
print()
print(f"Valor final: {tamanho_final_total:,} moleculas (base original + todas as "
      f"geracoes novas), um crescimento de {crescimento_total:.2%} sobre a base "
      f"de entrada.")